export enum Color {
  WHITE = "#FFFFFF",
  WHITE_TRANSPARENT = "#FFFFFFB2",
  HeaderText = "#13231B",
  SubheaderText = "#13231BB2",
  OnboardingButtonText = "#FFFFFF",
  OnboardingButtonBg = "#28AF6E",
  OnboardingButtonShadow = "#28AF6EA0",
  PaywallButtonBg = "#28AF6E",
  FooterText = "#597165B2",
  CategoryItemBorderColor = "#3C3C431A",
  CategoryItemBackgroundColor = "#F4F6F6",
  FeatureItemBackgroundColor = "#FFFFFF14",
  QuestionItemBorderColor = "#FFFFFF1A",
}
